In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np 
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [2]:
df=pd.DataFrame(
    {
        "soil_moisture": [0.10,0.15,0.20,0.25,0.40,0.60,0.35,0.18,0.45,0.05,0.80,0.27,0.55,0.70,0.12,0.30],
        "temp_c": [34,30,26,22,28,30,19,22,35,24,33,21,25,20,29,31],
        "sun_hours": [9,8,7,4,8,10,3,10,12,5,9,11,2,6,1,9],
        "need_water": [1,1,1,0,0,0,0,1,0,1,0,1,0,0,1,1]
    }
)
print(df)

    soil_moisture  temp_c  sun_hours  need_water
0            0.10      34          9           1
1            0.15      30          8           1
2            0.20      26          7           1
3            0.25      22          4           0
4            0.40      28          8           0
5            0.60      30         10           0
6            0.35      19          3           0
7            0.18      22         10           1
8            0.45      35         12           0
9            0.05      24          5           1
10           0.80      33          9           0
11           0.27      21         11           1
12           0.55      25          2           0
13           0.70      20          6           0
14           0.12      29          1           1
15           0.30      31          9           1

In [3]:
df.columns

Index(['soil_moisture', 'temp_c', 'sun_hours', 'need_water'], dtype='object')

In [4]:
x=df[['soil_moisture', 'temp_c', 'sun_hours']]
y=df["need_water"]
x

    soil_moisture  temp_c  sun_hours
0            0.10      34          9
1            0.15      30          8
2            0.20      26          7
3            0.25      22          4
4            0.40      28          8
5            0.60      30         10
6            0.35      19          3
7            0.18      22         10
8            0.45      35         12
9            0.05      24          5
10           0.80      33          9
11           0.27      21         11
12           0.55      25          2
13           0.70      20          6
14           0.12      29          1
15           0.30      31          9

usually normalization is used in DL, MIN-MAX scaler

In [5]:
x_min=x.min()
x_max=x.max()
x_scaled= (x-x_min)/(x_max - x_min + 1e-8)

In [6]:
x_scaled

    soil_moisture  temp_c  sun_hours
0        0.066667  0.9375   0.727273
1        0.133333  0.6875   0.636364
2        0.200000  0.4375   0.545455
3        0.266667  0.1875   0.272727
4        0.466667  0.5625   0.636364
5        0.733333  0.6875   0.818182
6        0.400000  0.0000   0.181818
7        0.173333  0.1875   0.818182
8        0.533333  1.0000   1.000000
9        0.000000  0.3125   0.363636
10       1.000000  0.8750   0.727273
11       0.293333  0.1250   0.909091
12       0.666667  0.3750   0.090909
13       0.866667  0.0625   0.454545
14       0.093333  0.6250   0.000000
15       0.333333  0.7500   0.727273

In [7]:
X_train, X_test, y_train, y_test = train_test_split( x_scaled, y, test_size=0.33, random_state=42)

In [14]:
model= keras.Sequential([
    layers.Input(shape=(X_train.shape[1], )),
    layers.Dense(3, activation= 'relu'),
    layers.Dense(1, activation= 'sigmoid')
])

In [15]:
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])
history= model.fit(
    X_train.values,y_train.values,
    validation_data= (X_test.values,y_test.values),
    epochs= 100,
    verbose=1,
    batch_size=4
)

Epoch 1/100
3/3 [==============================] - 1s 110ms/step - loss: 0.6487 - accuracy: 0.6000 - val_loss: 0.8757 - val_accuracy: 0.3333
Epoch 2/100
3/3 [==============================] - 0s 21ms/step - loss: 0.6479 - accuracy: 0.6000 - val_loss: 0.8600 - val_accuracy: 0.3333
Epoch 3/100
3/3 [==============================] - 0s 21ms/step - loss: 0.6413 - accuracy: 0.6000 - val_loss: 0.8498 - val_accuracy: 0.3333
Epoch 4/100
3/3 [==============================] - 0s 22ms/step - loss: 0.6376 - accuracy: 0.6000 - val_loss: 0.8424 - val_accuracy: 0.3333
Epoch 5/100
3/3 [==============================] - 0s 21ms/step - loss: 0.6361 - accuracy: 0.6000 - val_loss: 0.8401 - val_accuracy: 0.3333
Epoch 6/100
3/3 [==============================] - 0s 21ms/step - loss: 0.6356 - accuracy: 0.6000 - val_loss: 0.8380 - val_accuracy: 0.3333
Epoch 7/100
3/3 [==============================] - 0s 21ms/step - loss: 0.6358 - accuracy: 0.6000 - val_loss: 0.8257 - val_accuracy: 0.3333
Epoch 8/100
3/3 [==============================] - 0s 24ms/step - loss: 0.6305 - accuracy: 0.6000 - val_loss: 0.8179 - val_accuracy: 0.3333
Epoch 9/100
3/3 [==============================] - 0s 26ms/step - loss: 0.6300 - accuracy: 0.6000 - val_loss: 0.8083 - val_accuracy: 0.3333
Epoch 10/100
3/3 [==============================] - 0s 31ms/step - loss: 0.6263 - accuracy: 0.6000 - val_loss: 0.8071 - val_accuracy: 0.3333
Epoch 11/100
3/3 [==============================] - 0s 24ms/step - loss: 0.6258 - accuracy: 0.6000 - val_loss: 0.8058 - val_accuracy: 0.3333
Epoch 12/100
3/3 [==============================] - 0s 21ms/step - loss: 0.6271 - accuracy: 0.6000 - val_loss: 0.8011 - val_accuracy: 0.3333
Epoch 13/100
3/3 [==============================] - 0s 20ms/step - loss: 0.6238 - accuracy: 0.6000 - val_loss: 0.8000 - val_accuracy: 0.3333
Epoch 14/100
3/3 [==============================] - 0s 29ms/step - loss: 0.6246 - accuracy: 0.6000 - val_loss: 0.7994 - val_accuracy: 0.3333
Epoch 15/100
3/3 [==============================] - 0s 21ms/step - loss: 0.6239 - accuracy: 0.6000 - val_loss: 0.7987 - val_accuracy: 0.3333
Epoch 16/100
3/3 [==============================] - 0s 20ms/step - loss: 0.6222 - accuracy: 0.6000 - val_loss: 0.7943 - val_accuracy: 0.3333
Epoch 17/100
3/3 [==============================] - 0s 23ms/step - loss: 0.6220 - accuracy: 0.6000 - val_loss: 0.7839 - val_accuracy: 0.3333
Epoch 18/100
3/3 [==============================] - 0s 21ms/step - loss: 0.6186 - accuracy: 0.6000 - val_loss: 0.7801 - val_accuracy: 0.3333
Epoch 19/100
3/3 [==============================] - 0s 24ms/step - loss: 0.6183 - accuracy: 0.6000 - val_loss: 0.7727 - val_accuracy: 0.3333
Epoch 20/100
3/3 [==============================] - 0s 24ms/step - loss: 0.6164 - accuracy: 0.6000 - val_loss: 0.7693 - val_accuracy: 0.3333
Epoch 21/100
3/3 [==============================] - 0s 24ms/step - loss: 0.6169 - accuracy: 0.6000 - val_loss: 0.7694 - val_accuracy: 0.3333
Epoch 22/100
3/3 [==============================] - 0s 24ms/step - loss: 0.6150 - accuracy: 0.6000 - val_loss: 0.7661 - val_accuracy: 0.3333
Epoch 23/100
3/3 [==============================] - 0s 22ms/step - loss: 0.6141 - accuracy: 0.6000 - val_loss: 0.7623 - val_accuracy: 0.3333
Epoch 24/100
3/3 [==============================] - 0s 24ms/step - loss: 0.6134 - accuracy: 0.6000 - val_loss: 0.7625 - val_accuracy: 0.3333
Epoch 25/100
3/3 [==============================] - 0s 25ms/step - loss: 0.6129 - accuracy: 0.6000 - val_loss: 0.7596 - val_accuracy: 0.3333
Epoch 26/100
3/3 [==============================] - 0s 23ms/step - loss: 0.6146 - accuracy: 0.6000 - val_loss: 0.7568 - val_accuracy: 0.3333
Epoch 27/100
3/3 [==============================] - 0s 24ms/step - loss: 0.6114 - accuracy: 0.6000 - val_loss: 0.7536 - val_accuracy: 0.3333
Epoch 28/100
3/3 [==============================] - 0s 24ms/step - loss: 0.6105 - accuracy: 0.6000 - val_loss: 0.7491 - val_accuracy: 0.3333
Epoch 29/100
3/3 [==============================] - 0s 23ms/step - loss: 0.6097 - accuracy: 0.6000 - val_loss: 0.7458 - val_accuracy: 0.3333
Epoch 30/100
3/3 [==============================] - 0s 24ms/step - loss: 0.6089 - accuracy: 0.6000 - val_loss: 0.7419 - val_accuracy: 0.3333
Epoch 31/100
3/3 [==============================] - 0s 23ms/step - loss: 0.6092 - accuracy: 0.6000 - val_loss: 0.7427 - val_accuracy: 0.3333
Epoch 32/100
3/3 [==============================] - 0s 20ms/step - loss: 0.6090 - accuracy: 0.6000 - val_loss: 0.7436 - val_accuracy: 0.3333
Epoch 33/100
3/3 [==============================] - 0s 22ms/step - loss: 0.6074 - accuracy: 0.6000 - val_loss: 0.7440 - val_accuracy: 0.3333
Epoch 34/100
3/3 [==============================] - 0s 23ms/step - loss: 0.6073 - accuracy: 0.6000 - val_loss: 0.7446 - val_accuracy: 0.3333
Epoch 35/100
3/3 [==============================] - 0s 23ms/step - loss: 0.6069 - accuracy: 0.6000 - val_loss: 0.7455 - val_accuracy: 0.3333
Epoch 36/100
3/3 [==============================] - 0s 24ms/step - loss: 0.6065 - accuracy: 0.6000 - val_loss: 0.7458 - val_accuracy: 0.3333
Epoch 37/100
3/3 [==============================] - 0s 23ms/step - loss: 0.6068 - accuracy: 0.6000 - val_loss: 0.7464 - val_accuracy: 0.3333
Epoch 38/100
3/3 [==============================] - 0s 23ms/step - loss: 0.6102 - accuracy: 0.6000 - val_loss: 0.7467 - val_accuracy: 0.3333
Epoch 39/100
3/3 [==============================] - 0s 21ms/step - loss: 0.6048 - accuracy: 0.6000 - val_loss: 0.7433 - val_accuracy: 0.3333
Epoch 40/100
3/3 [==============================] - 0s 22ms/step - loss: 0.6047 - accuracy: 0.6000 - val_loss: 0.7442 - val_accuracy: 0.3333
Epoch 41/100
3/3 [==============================] - 0s 21ms/step - loss: 0.6061 - accuracy: 0.6000 - val_loss: 0.7409 - val_accuracy: 0.3333
Epoch 42/100
3/3 [==============================] - 0s 51ms/step - loss: 0.6033 - accuracy: 0.6000 - val_loss: 0.7365 - val_accuracy: 0.3333
Epoch 43/100
3/3 [==============================] - 0s 22ms/step - loss: 0.6024 - accuracy: 0.6000 - val_loss: 0.7339 - val_accuracy: 0.3333
Epoch 44/100
3/3 [==============================] - 0s 27ms/step - loss: 0.6018 - accuracy: 0.6000 - val_loss: 0.7343 - val_accuracy: 0.3333
Epoch 45/100
3/3 [==============================] - 0s 25ms/step - loss: 0.6010 - accuracy: 0.6000 - val_loss: 0.7317 - val_accuracy: 0.3333
Epoch 46/100
3/3 [==============================] - 0s 23ms/step - loss: 0.6007 - accuracy: 0.6000 - val_loss: 0.7284 - val_accuracy: 0.3333
Epoch 47/100
3/3 [==============================] - 0s 23ms/step - loss: 0.5998 - accuracy: 0.6000 - val_loss: 0.7264 - val_accuracy: 0.3333
Epoch 48/100
3/3 [==============================] - 0s 20ms/step - loss: 0.5995 - accuracy: 0.6000 - val_loss: 0.7208 - val_accuracy: 0.3333
Epoch 49/100
3/3 [==============================] - 0s 21ms/step - loss: 0.5984 - accuracy: 0.6000 - val_loss: 0.7171 - val_accuracy: 0.3333
Epoch 50/100
3/3 [==============================] - 0s 21ms/step - loss: 0.5974 - accuracy: 0.6000 - val_loss: 0.7151 - val_accuracy: 0.3333
Epoch 51/100
3/3 [==============================] - 0s 23ms/step - loss: 0.5977 - accuracy: 0.6000 - val_loss: 0.7088 - val_accuracy: 0.3333
Epoch 52/100
3/3 [==============================] - 0s 24ms/step - loss: 0.5981 - accuracy: 0.6000 - val_loss: 0.7069 - val_accuracy: 0.3333
Epoch 53/100
3/3 [==============================] - 0s 23ms/step - loss: 0.5954 - accuracy: 0.7000 - val_loss: 0.7037 - val_accuracy: 0.3333
Epoch 54/100
3/3 [==============================] - 0s 23ms/step - loss: 0.5950 - accuracy: 0.7000 - val_loss: 0.7053 - val_accuracy: 0.3333
Epoch 55/100
3/3 [==============================] - 0s 22ms/step - loss: 0.5940 - accuracy: 0.7000 - val_loss: 0.7038 - val_accuracy: 0.3333
Epoch 56/100
3/3 [==============================] - 0s 22ms/step - loss: 0.5936 - accuracy: 0.7000 - val_loss: 0.7022 - val_accuracy: 0.3333
Epoch 57/100
3/3 [==============================] - 0s 23ms/step - loss: 0.5934 - accuracy: 0.7000 - val_loss: 0.7035 - val_accuracy: 0.3333
Epoch 58/100
3/3 [==============================] - 0s 23ms/step - loss: 0.5948 - accuracy: 0.7000 - val_loss: 0.7012 - val_accuracy: 0.3333
Epoch 59/100
3/3 [==============================] - 0s 27ms/step - loss: 0.5922 - accuracy: 0.7000 - val_loss: 0.6992 - val_accuracy: 0.3333
Epoch 60/100
3/3 [==============================] - 0s 26ms/step - loss: 0.5931 - accuracy: 0.7000 - val_loss: 0.7008 - val_accuracy: 0.3333
Epoch 61/100
3/3 [==============================] - 0s 21ms/step - loss: 0.5910 - accuracy: 0.7000 - val_loss: 0.6980 - val_accuracy: 0.3333
Epoch 62/100
3/3 [==============================] - 0s 23ms/step - loss: 0.5917 - accuracy: 0.7000 - val_loss: 0.6996 - val_accuracy: 0.3333
Epoch 63/100
3/3 [==============================] - 0s 24ms/step - loss: 0.5898 - accuracy: 0.7000 - val_loss: 0.6974 - val_accuracy: 0.3333
Epoch 64/100
3/3 [==============================] - 0s 26ms/step - loss: 0.5910 - accuracy: 0.7000 - val_loss: 0.6927 - val_accuracy: 0.3333
Epoch 65/100
3/3 [==============================] - 0s 22ms/step - loss: 0.5885 - accuracy: 0.7000 - val_loss: 0.6909 - val_accuracy: 0.3333
Epoch 66/100
3/3 [==============================] - 0s 20ms/step - loss: 0.5909 - accuracy: 0.7000 - val_loss: 0.6892 - val_accuracy: 0.3333
Epoch 67/100
3/3 [==============================] - 0s 20ms/step - loss: 0.5877 - accuracy: 0.7000 - val_loss: 0.6872 - val_accuracy: 0.3333
Epoch 68/100
3/3 [==============================] - 0s 20ms/step - loss: 0.5875 - accuracy: 0.7000 - val_loss: 0.6858 - val_accuracy: 0.3333
Epoch 69/100
3/3 [==============================] - 0s 20ms/step - loss: 0.5875 - accuracy: 0.7000 - val_loss: 0.6874 - val_accuracy: 0.3333
Epoch 70/100
3/3 [==============================] - 0s 22ms/step - loss: 0.5875 - accuracy: 0.7000 - val_loss: 0.6822 - val_accuracy: 0.3333
Epoch 71/100
3/3 [==============================] - 0s 21ms/step - loss: 0.5867 - accuracy: 0.7000 - val_loss: 0.6766 - val_accuracy: 0.3333
Epoch 72/100
3/3 [==============================] - 0s 22ms/step - loss: 0.5847 - accuracy: 0.8000 - val_loss: 0.6754 - val_accuracy: 0.3333
Epoch 73/100
3/3 [==============================] - 0s 21ms/step - loss: 0.5855 - accuracy: 0.7000 - val_loss: 0.6773 - val_accuracy: 0.3333
Epoch 74/100
3/3 [==============================] - 0s 27ms/step - loss: 0.5850 - accuracy: 0.7000 - val_loss: 0.6791 - val_accuracy: 0.3333
Epoch 75/100
3/3 [==============================] - 0s 29ms/step - loss: 0.5835 - accuracy: 0.7000 - val_loss: 0.6775 - val_accuracy: 0.3333
Epoch 76/100
3/3 [==============================] - 0s 31ms/step - loss: 0.5832 - accuracy: 0.7000 - val_loss: 0.6751 - val_accuracy: 0.3333
Epoch 77/100
3/3 [==============================] - 0s 25ms/step - loss: 0.5845 - accuracy: 0.7000 - val_loss: 0.6696 - val_accuracy: 0.3333
Epoch 78/100
3/3 [==============================] - 0s 26ms/step - loss: 0.5824 - accuracy: 0.8000 - val_loss: 0.6712 - val_accuracy: 0.3333
Epoch 79/100
3/3 [==============================] - 0s 27ms/step - loss: 0.5824 - accuracy: 0.8000 - val_loss: 0.6652 - val_accuracy: 0.3333
Epoch 80/100
3/3 [==============================] - 0s 26ms/step - loss: 0.5804 - accuracy: 0.8000 - val_loss: 0.6645 - val_accuracy: 0.3333
Epoch 81/100
3/3 [==============================] - 0s 26ms/step - loss: 0.5804 - accuracy: 0.8000 - val_loss: 0.6666 - val_accuracy: 0.3333
Epoch 82/100
3/3 [==============================] - 0s 27ms/step - loss: 0.5796 - accuracy: 0.8000 - val_loss: 0.6651 - val_accuracy: 0.3333
Epoch 83/100
3/3 [==============================] - 0s 27ms/step - loss: 0.5794 - accuracy: 0.8000 - val_loss: 0.6623 - val_accuracy: 0.3333
Epoch 84/100
3/3 [==============================] - 0s 24ms/step - loss: 0.5788 - accuracy: 0.8000 - val_loss: 0.6610 - val_accuracy: 0.3333
Epoch 85/100
3/3 [==============================] - 0s 27ms/step - loss: 0.5800 - accuracy: 0.8000 - val_loss: 0.6594 - val_accuracy: 0.3333
Epoch 86/100
3/3 [==============================] - 0s 25ms/step - loss: 0.5803 - accuracy: 0.8000 - val_loss: 0.6584 - val_accuracy: 0.3333
Epoch 87/100
3/3 [==============================] - 0s 25ms/step - loss: 0.5791 - accuracy: 0.8000 - val_loss: 0.6537 - val_accuracy: 0.3333
Epoch 88/100
3/3 [==============================] - 0s 25ms/step - loss: 0.5784 - accuracy: 0.8000 - val_loss: 0.6553 - val_accuracy: 0.3333
Epoch 89/100
3/3 [==============================] - 0s 25ms/step - loss: 0.5762 - accuracy: 0.8000 - val_loss: 0.6566 - val_accuracy: 0.3333
Epoch 90/100
3/3 [==============================] - 0s 25ms/step - loss: 0.5756 - accuracy: 0.8000 - val_loss: 0.6545 - val_accuracy: 0.3333
Epoch 91/100
3/3 [==============================] - 0s 23ms/step - loss: 0.5767 - accuracy: 0.8000 - val_loss: 0.6560 - val_accuracy: 0.3333
Epoch 92/100
3/3 [==============================] - 0s 28ms/step - loss: 0.5743 - accuracy: 0.8000 - val_loss: 0.6539 - val_accuracy: 0.3333
Epoch 93/100
3/3 [==============================] - 0s 30ms/step - loss: 0.5738 - accuracy: 0.8000 - val_loss: 0.6524 - val_accuracy: 0.3333
Epoch 94/100
3/3 [==============================] - 0s 25ms/step - loss: 0.5755 - accuracy: 0.8000 - val_loss: 0.6478 - val_accuracy: 0.5000
Epoch 95/100
3/3 [==============================] - 0s 24ms/step - loss: 0.5733 - accuracy: 0.8000 - val_loss: 0.6466 - val_accuracy: 0.5000
Epoch 96/100
3/3 [==============================] - 0s 25ms/step - loss: 0.5750 - accuracy: 0.8000 - val_loss: 0.6464 - val_accuracy: 0.5000
Epoch 97/100
3/3 [==============================] - 0s 30ms/step - loss: 0.5735 - accuracy: 0.8000 - val_loss: 0.6425 - val_accuracy: 0.5000
Epoch 98/100
3/3 [==============================] - 0s 21ms/step - loss: 0.5716 - accuracy: 0.8000 - val_loss: 0.6409 - val_accuracy: 0.5000
Epoch 99/100
3/3 [==============================] - 0s 20ms/step - loss: 0.5710 - accuracy: 0.8000 - val_loss: 0.6401 - val_accuracy: 0.5000
Epoch 100/100
3/3 [==============================] - 0s 19ms/step - loss: 0.5718 - accuracy: 0.8000 - val_loss: 0.6349 - val_accuracy: 0.5000

In [16]:
from tensorflow.keras import optimizers
opt= optimizers.SGD(learning_rate= 0.01, momentum= 0.9)

In [17]:
model.compile(optimizer=opt , loss='binary_crossentropy', metrics=['accuracy'])
history= model.fit(
    X_train.values,y_train.values,
    validation_data= (X_test.values,y_test.values),
    epochs= 100,
    verbose=1,
    batch_size=5
)

Epoch 1/100
2/2 [==============================] - 1s 167ms/step - loss: 0.5706 - accuracy: 0.8000 - val_loss: 0.6331 - val_accuracy: 0.5000
Epoch 2/100
2/2 [==============================] - 0s 36ms/step - loss: 0.5701 - accuracy: 0.8000 - val_loss: 0.6311 - val_accuracy: 0.5000
Epoch 3/100
2/2 [==============================] - 0s 44ms/step - loss: 0.5691 - accuracy: 0.8000 - val_loss: 0.6331 - val_accuracy: 0.5000
Epoch 4/100
2/2 [==============================] - 0s 44ms/step - loss: 0.5672 - accuracy: 0.8000 - val_loss: 0.6336 - val_accuracy: 0.5000
Epoch 5/100
2/2 [==============================] - 0s 41ms/step - loss: 0.5648 - accuracy: 0.8000 - val_loss: 0.6309 - val_accuracy: 0.5000
Epoch 6/100
2/2 [==============================] - 0s 41ms/step - loss: 0.5625 - accuracy: 0.8000 - val_loss: 0.6284 - val_accuracy: 0.5000
Epoch 7/100
2/2 [==============================] - 0s 43ms/step - loss: 0.5604 - accuracy: 0.8000 - val_loss: 0.6246 - val_accuracy: 0.5000
Epoch 8/100
2/2 [==============================] - 0s 41ms/step - loss: 0.5589 - accuracy: 0.8000 - val_loss: 0.6240 - val_accuracy: 0.5000
Epoch 9/100
2/2 [==============================] - 0s 42ms/step - loss: 0.5554 - accuracy: 0.8000 - val_loss: 0.6201 - val_accuracy: 0.5000
Epoch 10/100
2/2 [==============================] - 0s 39ms/step - loss: 0.5531 - accuracy: 0.8000 - val_loss: 0.6174 - val_accuracy: 0.5000
Epoch 11/100
2/2 [==============================] - 0s 39ms/step - loss: 0.5529 - accuracy: 0.8000 - val_loss: 0.6072 - val_accuracy: 0.5000
Epoch 12/100
2/2 [==============================] - 0s 41ms/step - loss: 0.5476 - accuracy: 0.8000 - val_loss: 0.6049 - val_accuracy: 0.5000
Epoch 13/100
2/2 [==============================] - 0s 40ms/step - loss: 0.5433 - accuracy: 0.8000 - val_loss: 0.5990 - val_accuracy: 0.5000
Epoch 14/100
2/2 [==============================] - 0s 43ms/step - loss: 0.5418 - accuracy: 0.8000 - val_loss: 0.5904 - val_accuracy: 0.5000
Epoch 15/100
2/2 [==============================] - 0s 40ms/step - loss: 0.5374 - accuracy: 0.8000 - val_loss: 0.5846 - val_accuracy: 0.5000
Epoch 16/100
2/2 [==============================] - 0s 42ms/step - loss: 0.5351 - accuracy: 0.8000 - val_loss: 0.5826 - val_accuracy: 0.5000
Epoch 17/100
2/2 [==============================] - 0s 40ms/step - loss: 0.5309 - accuracy: 0.8000 - val_loss: 0.5772 - val_accuracy: 0.5000
Epoch 18/100
2/2 [==============================] - 0s 37ms/step - loss: 0.5282 - accuracy: 0.8000 - val_loss: 0.5695 - val_accuracy: 0.5000
Epoch 19/100
2/2 [==============================] - 0s 38ms/step - loss: 0.5251 - accuracy: 0.8000 - val_loss: 0.5671 - val_accuracy: 0.5000
Epoch 20/100
2/2 [==============================] - 0s 38ms/step - loss: 0.5218 - accuracy: 0.8000 - val_loss: 0.5647 - val_accuracy: 0.6667
Epoch 21/100
2/2 [==============================] - 0s 38ms/step - loss: 0.5180 - accuracy: 0.8000 - val_loss: 0.5609 - val_accuracy: 0.8333
Epoch 22/100
2/2 [==============================] - 0s 38ms/step - loss: 0.5140 - accuracy: 0.8000 - val_loss: 0.5551 - val_accuracy: 0.8333
Epoch 23/100
2/2 [==============================] - 0s 37ms/step - loss: 0.5108 - accuracy: 0.9000 - val_loss: 0.5492 - val_accuracy: 0.8333
Epoch 24/100
2/2 [==============================] - 0s 39ms/step - loss: 0.5074 - accuracy: 0.9000 - val_loss: 0.5439 - val_accuracy: 0.8333
Epoch 25/100
2/2 [==============================] - 0s 37ms/step - loss: 0.5053 - accuracy: 0.9000 - val_loss: 0.5345 - val_accuracy: 0.8333
Epoch 26/100
2/2 [==============================] - 0s 41ms/step - loss: 0.5014 - accuracy: 0.9000 - val_loss: 0.5309 - val_accuracy: 0.8333
Epoch 27/100
2/2 [==============================] - 0s 38ms/step - loss: 0.4976 - accuracy: 0.9000 - val_loss: 0.5234 - val_accuracy: 0.8333
Epoch 28/100
2/2 [==============================] - 0s 38ms/step - loss: 0.4941 - accuracy: 0.9000 - val_loss: 0.5180 - val_accuracy: 0.8333
Epoch 29/100
2/2 [==============================] - 0s 37ms/step - loss: 0.4904 - accuracy: 0.9000 - val_loss: 0.5131 - val_accuracy: 0.8333
Epoch 30/100
2/2 [==============================] - 0s 41ms/step - loss: 0.4878 - accuracy: 0.9000 - val_loss: 0.5104 - val_accuracy: 0.8333
Epoch 31/100
2/2 [==============================] - 0s 39ms/step - loss: 0.4837 - accuracy: 0.9000 - val_loss: 0.5042 - val_accuracy: 0.8333
Epoch 32/100
2/2 [==============================] - 0s 37ms/step - loss: 0.4803 - accuracy: 0.9000 - val_loss: 0.5003 - val_accuracy: 0.8333
Epoch 33/100
2/2 [==============================] - 0s 39ms/step - loss: 0.4769 - accuracy: 0.9000 - val_loss: 0.4953 - val_accuracy: 0.8333
Epoch 34/100
2/2 [==============================] - 0s 36ms/step - loss: 0.4730 - accuracy: 0.9000 - val_loss: 0.4917 - val_accuracy: 0.8333
Epoch 35/100
2/2 [==============================] - 0s 39ms/step - loss: 0.4702 - accuracy: 0.9000 - val_loss: 0.4856 - val_accuracy: 0.8333
Epoch 36/100
2/2 [==============================] - 0s 40ms/step - loss: 0.4677 - accuracy: 0.9000 - val_loss: 0.4783 - val_accuracy: 0.8333
Epoch 37/100
2/2 [==============================] - 0s 40ms/step - loss: 0.4633 - accuracy: 0.9000 - val_loss: 0.4765 - val_accuracy: 0.8333
Epoch 38/100
2/2 [==============================] - 0s 37ms/step - loss: 0.4598 - accuracy: 0.9000 - val_loss: 0.4722 - val_accuracy: 0.8333
Epoch 39/100
2/2 [==============================] - 0s 37ms/step - loss: 0.4562 - accuracy: 0.9000 - val_loss: 0.4683 - val_accuracy: 0.8333
Epoch 40/100
2/2 [==============================] - 0s 37ms/step - loss: 0.4532 - accuracy: 0.9000 - val_loss: 0.4647 - val_accuracy: 0.8333
Epoch 41/100
2/2 [==============================] - 0s 38ms/step - loss: 0.4507 - accuracy: 0.9000 - val_loss: 0.4581 - val_accuracy: 0.8333
Epoch 42/100
2/2 [==============================] - 0s 38ms/step - loss: 0.4476 - accuracy: 0.9000 - val_loss: 0.4517 - val_accuracy: 0.8333
Epoch 43/100
2/2 [==============================] - 0s 39ms/step - loss: 0.4429 - accuracy: 0.9000 - val_loss: 0.4494 - val_accuracy: 0.8333
Epoch 44/100
2/2 [==============================] - 0s 38ms/step - loss: 0.4402 - accuracy: 0.9000 - val_loss: 0.4484 - val_accuracy: 0.8333
Epoch 45/100
2/2 [==============================] - 0s 38ms/step - loss: 0.4374 - accuracy: 0.9000 - val_loss: 0.4417 - val_accuracy: 0.8333
Epoch 46/100
2/2 [==============================] - 0s 38ms/step - loss: 0.4347 - accuracy: 0.9000 - val_loss: 0.4347 - val_accuracy: 0.8333
Epoch 47/100
2/2 [==============================] - 0s 39ms/step - loss: 0.4298 - accuracy: 0.9000 - val_loss: 0.4315 - val_accuracy: 0.8333
Epoch 48/100
2/2 [==============================] - 0s 39ms/step - loss: 0.4280 - accuracy: 0.9000 - val_loss: 0.4325 - val_accuracy: 0.8333
Epoch 49/100
2/2 [==============================] - 0s 37ms/step - loss: 0.4234 - accuracy: 0.9000 - val_loss: 0.4284 - val_accuracy: 0.8333
Epoch 50/100
2/2 [==============================] - 0s 37ms/step - loss: 0.4211 - accuracy: 0.9000 - val_loss: 0.4272 - val_accuracy: 0.8333
Epoch 51/100
2/2 [==============================] - 0s 40ms/step - loss: 0.4174 - accuracy: 0.9000 - val_loss: 0.4238 - val_accuracy: 0.8333
Epoch 52/100
2/2 [==============================] - 0s 38ms/step - loss: 0.4178 - accuracy: 0.9000 - val_loss: 0.4240 - val_accuracy: 0.8333
Epoch 53/100
2/2 [==============================] - 0s 41ms/step - loss: 0.4114 - accuracy: 0.9000 - val_loss: 0.4147 - val_accuracy: 0.8333
Epoch 54/100
2/2 [==============================] - 0s 37ms/step - loss: 0.4079 - accuracy: 0.9000 - val_loss: 0.4103 - val_accuracy: 0.8333
Epoch 55/100
2/2 [==============================] - 0s 39ms/step - loss: 0.4048 - accuracy: 0.9000 - val_loss: 0.4014 - val_accuracy: 0.8333
Epoch 56/100
2/2 [==============================] - 0s 38ms/step - loss: 0.4011 - accuracy: 0.9000 - val_loss: 0.3950 - val_accuracy: 0.8333
Epoch 57/100
2/2 [==============================] - 0s 39ms/step - loss: 0.4003 - accuracy: 0.9000 - val_loss: 0.3853 - val_accuracy: 0.8333
Epoch 58/100
2/2 [==============================] - 0s 38ms/step - loss: 0.3952 - accuracy: 0.9000 - val_loss: 0.3821 - val_accuracy: 0.8333
Epoch 59/100
2/2 [==============================] - 0s 39ms/step - loss: 0.3922 - accuracy: 0.9000 - val_loss: 0.3792 - val_accuracy: 0.8333
Epoch 60/100
2/2 [==============================] - 0s 45ms/step - loss: 0.3918 - accuracy: 0.9000 - val_loss: 0.3802 - val_accuracy: 0.8333
Epoch 61/100
2/2 [==============================] - 0s 39ms/step - loss: 0.3859 - accuracy: 0.9000 - val_loss: 0.3765 - val_accuracy: 0.8333
Epoch 62/100
2/2 [==============================] - 0s 38ms/step - loss: 0.3841 - accuracy: 0.9000 - val_loss: 0.3754 - val_accuracy: 0.8333
Epoch 63/100
2/2 [==============================] - 0s 39ms/step - loss: 0.3808 - accuracy: 0.9000 - val_loss: 0.3731 - val_accuracy: 0.8333
Epoch 64/100
2/2 [==============================] - 0s 40ms/step - loss: 0.3770 - accuracy: 0.9000 - val_loss: 0.3672 - val_accuracy: 0.8333
Epoch 65/100
2/2 [==============================] - 0s 38ms/step - loss: 0.3746 - accuracy: 0.9000 - val_loss: 0.3641 - val_accuracy: 0.8333
Epoch 66/100
2/2 [==============================] - 0s 38ms/step - loss: 0.3725 - accuracy: 0.9000 - val_loss: 0.3562 - val_accuracy: 0.8333
Epoch 67/100
2/2 [==============================] - 0s 37ms/step - loss: 0.3685 - accuracy: 0.9000 - val_loss: 0.3516 - val_accuracy: 0.8333
Epoch 68/100
2/2 [==============================] - 0s 39ms/step - loss: 0.3669 - accuracy: 0.9000 - val_loss: 0.3509 - val_accuracy: 0.8333
Epoch 69/100
2/2 [==============================] - 0s 38ms/step - loss: 0.3632 - accuracy: 0.9000 - val_loss: 0.3485 - val_accuracy: 0.8333
Epoch 70/100
2/2 [==============================] - 0s 38ms/step - loss: 0.3601 - accuracy: 0.9000 - val_loss: 0.3441 - val_accuracy: 0.8333
Epoch 71/100
2/2 [==============================] - 0s 39ms/step - loss: 0.3573 - accuracy: 0.9000 - val_loss: 0.3398 - val_accuracy: 0.8333
Epoch 72/100
2/2 [==============================] - 0s 38ms/step - loss: 0.3546 - accuracy: 0.9000 - val_loss: 0.3354 - val_accuracy: 0.8333
Epoch 73/100
2/2 [==============================] - 0s 38ms/step - loss: 0.3521 - accuracy: 0.9000 - val_loss: 0.3327 - val_accuracy: 0.8333
Epoch 74/100
2/2 [==============================] - 0s 38ms/step - loss: 0.3496 - accuracy: 0.9000 - val_loss: 0.3288 - val_accuracy: 0.8333
Epoch 75/100
2/2 [==============================] - 0s 38ms/step - loss: 0.3507 - accuracy: 0.9000 - val_loss: 0.3328 - val_accuracy: 0.8333
Epoch 76/100
2/2 [==============================] - 0s 40ms/step - loss: 0.3441 - accuracy: 0.9000 - val_loss: 0.3298 - val_accuracy: 0.8333
Epoch 77/100
2/2 [==============================] - 0s 39ms/step - loss: 0.3417 - accuracy: 0.9000 - val_loss: 0.3251 - val_accuracy: 0.8333
Epoch 78/100
2/2 [==============================] - 0s 39ms/step - loss: 0.3406 - accuracy: 0.9000 - val_loss: 0.3189 - val_accuracy: 0.8333
Epoch 79/100
2/2 [==============================] - 0s 38ms/step - loss: 0.3362 - accuracy: 0.9000 - val_loss: 0.3175 - val_accuracy: 0.8333
Epoch 80/100
2/2 [==============================] - 0s 42ms/step - loss: 0.3340 - accuracy: 0.9000 - val_loss: 0.3148 - val_accuracy: 0.8333
Epoch 81/100
2/2 [==============================] - 0s 40ms/step - loss: 0.3317 - accuracy: 0.9000 - val_loss: 0.3114 - val_accuracy: 0.8333
Epoch 82/100
2/2 [==============================] - 0s 43ms/step - loss: 0.3300 - accuracy: 0.9000 - val_loss: 0.3133 - val_accuracy: 0.8333
Epoch 83/100
2/2 [==============================] - 0s 56ms/step - loss: 0.3280 - accuracy: 0.9000 - val_loss: 0.3151 - val_accuracy: 0.8333
Epoch 84/100
2/2 [==============================] - 0s 52ms/step - loss: 0.3252 - accuracy: 0.9000 - val_loss: 0.3149 - val_accuracy: 0.8333
Epoch 85/100
2/2 [==============================] - 0s 50ms/step - loss: 0.3218 - accuracy: 0.9000 - val_loss: 0.3111 - val_accuracy: 0.8333
Epoch 86/100
2/2 [==============================] - 0s 50ms/step - loss: 0.3192 - accuracy: 0.9000 - val_loss: 0.3068 - val_accuracy: 0.8333
Epoch 87/100
2/2 [==============================] - 0s 50ms/step - loss: 0.3180 - accuracy: 0.9000 - val_loss: 0.2995 - val_accuracy: 0.8333
Epoch 88/100
2/2 [==============================] - 0s 44ms/step - loss: 0.3165 - accuracy: 0.9000 - val_loss: 0.2920 - val_accuracy: 0.8333
Epoch 89/100
2/2 [==============================] - 0s 39ms/step - loss: 0.3124 - accuracy: 1.0000 - val_loss: 0.2893 - val_accuracy: 0.8333
Epoch 90/100
2/2 [==============================] - 0s 38ms/step - loss: 0.3106 - accuracy: 1.0000 - val_loss: 0.2896 - val_accuracy: 0.8333
Epoch 91/100
2/2 [==============================] - 0s 38ms/step - loss: 0.3084 - accuracy: 1.0000 - val_loss: 0.2895 - val_accuracy: 0.8333
Epoch 92/100
2/2 [==============================] - 0s 37ms/step - loss: 0.3056 - accuracy: 1.0000 - val_loss: 0.2882 - val_accuracy: 0.8333
Epoch 93/100
2/2 [==============================] - 0s 42ms/step - loss: 0.3033 - accuracy: 1.0000 - val_loss: 0.2846 - val_accuracy: 0.8333
Epoch 94/100
2/2 [==============================] - 0s 48ms/step - loss: 0.3042 - accuracy: 1.0000 - val_loss: 0.2778 - val_accuracy: 0.8333
Epoch 95/100
2/2 [==============================] - 0s 128ms/step - loss: 0.3008 - accuracy: 1.0000 - val_loss: 0.2734 - val_accuracy: 0.8333
Epoch 96/100
2/2 [==============================] - 0s 58ms/step - loss: 0.2977 - accuracy: 1.0000 - val_loss: 0.2714 - val_accuracy: 0.8333
Epoch 97/100
2/2 [==============================] - 0s 58ms/step - loss: 0.2950 - accuracy: 1.0000 - val_loss: 0.2713 - val_accuracy: 0.8333
Epoch 98/100
2/2 [==============================] - 0s 54ms/step - loss: 0.2929 - accuracy: 1.0000 - val_loss: 0.2726 - val_accuracy: 0.8333
Epoch 99/100
2/2 [==============================] - 0s 51ms/step - loss: 0.2912 - accuracy: 1.0000 - val_loss: 0.2748 - val_accuracy: 0.8333
Epoch 100/100
2/2 [==============================] - 0s 52ms/step - loss: 0.2889 - accuracy: 1.0000 - val_loss: 0.2755 - val_accuracy: 0.8333