>> Grid Search Cross Validation

In [42]:
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import pandas as pd

In [43]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [44]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [45]:
from sklearn.model_selection import train_test_split
x = df.drop('species', axis=1)
y = df['species']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [46]:

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)
y_pred=knn.predict(X_test)
score=knn.score(X_test, y_test)
print(score)

0.98

In [48]:
from sklearn.svm import SVC
svc=SVC(C=10, kernel='rbf', gamma=0.1)
svc.fit(X_train, y_train)

SVC(C=10, gamma=0.1)

> Using Grid search cv

In [49]:
from sklearn.model_selection import GridSearchCV

In [50]:
classifier=GridSearchCV((knn),{
    'n_neighbors':[1,3,5,7,9],} ,cv=5)
classifier.fit(X_train, y_train)
print(classifier.best_params_)

{'n_neighbors': 1}

In [54]:
classifier=GridSearchCV((svc),{
    'C':[0.1,1,10,100],
    'kernel':['linear','rbf'],
    'gamma':[0.001,0.01,0.1,1]
}, cv=5)
classifier.fit(x, y)
print(classifier.best_params_)

{'C': 1, 'gamma': 0.001, 'kernel': 'linear'}

In [55]:
results=pd.DataFrame(classifier.cv_results_)
results.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010775,0.001356,0.010132,0.001792,0.1,0.001,linear,"{'C': 0.1, 'gamma': 0.001, 'kernel': 'linear'}",0.966667,0.966667,0.966667,0.966667,1.000000,0.973333,0.013333,10
1,0.011672,0.003024,0.006703,0.002411,0.1,0.001,rbf,"{'C': 0.1, 'gamma': 0.001, 'kernel': 'rbf'}",0.866667,0.966667,0.833333,0.966667,0.933333,0.913333,0.054160,30
2,0.003642,0.000539,0.003211,0.000439,0.1,0.01,linear,"{'C': 0.1, 'gamma': 0.01, 'kernel': 'linear'}",0.966667,0.966667,0.966667,0.966667,1.000000,0.973333,0.013333,10
3,0.004316,0.000391,0.003094,0.000638,0.1,0.01,rbf,"{'C': 0.1, 'gamma': 0.01, 'kernel': 'rbf'}",0.866667,0.966667,0.833333,0.966667,0.933333,0.913333,0.054160,30
4,0.003250,0.000413,0.002662,0.000488,0.1,0.1,linear,"{'C': 0.1, 'gamma': 0.1, 'kernel': 'linear'}",0.966667,0.966667,0.966667,0.966667,1.000000,0.973333,0.013333,10

In [61]:
results[['param_C','param_gamma','param_kernel','mean_test_score']].sort_values(by= 'mean_test_score', ascending = False)

   param_C param_gamma param_kernel  mean_test_score
13       1         0.1          rbf         0.980000
27     100        0.01          rbf         0.980000
25     100       0.001          rbf         0.980000
21      10         0.1          rbf         0.980000
19      10        0.01          rbf         0.980000
8        1       0.001       linear         0.980000
10       1        0.01       linear         0.980000
14       1           1       linear         0.980000
12       1         0.1       linear         0.980000
0      0.1       0.001       linear         0.973333
22      10           1       linear         0.973333
20      10         0.1       linear         0.973333
18      10        0.01       linear         0.973333
16      10       0.001       linear         0.973333
6      0.1           1       linear         0.973333
2      0.1        0.01       linear         0.973333
4      0.1         0.1       linear         0.973333
15       1           1          rbf         0.966667
26     100        0.01       linear         0.966667
30     100           1       linear         0.966667
29     100         0.1          rbf         0.966667
28     100         0.1       linear         0.966667
24     100       0.001       linear         0.966667
7      0.1           1          rbf         0.960000
23      10           1          rbf         0.953333
31     100           1          rbf         0.940000
17      10       0.001          rbf         0.933333
11       1        0.01          rbf         0.933333
5      0.1         0.1          rbf         0.920000
3      0.1        0.01          rbf         0.913333
9        1       0.001          rbf         0.913333
1      0.1       0.001          rbf         0.913333